CREATE ROLE nasa_write NOLOGIN INHERIT;

-- public SCHEMA
GRANT UPDATE, INSERT, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public TO nasa_write;
GRANT CREATE ON SCHEMA public TO nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT UPDATE, INSERT, DELETE, REFERENCES ON TABLES TO nasa_write;

-- data SCHEMA
GRANT UPDATE, INSERT, DELETE, REFERENCES ON ALL TABLES IN SCHEMA data TO nasa_write;
GRANT CREATE ON SCHEMA data TO nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA data GRANT UPDATE, INSERT, DELETE, REFERENCES ON TABLES TO nasa_write;

