REVOKE ALL ON DATABASE nasa FROM nasa_write;

-- public SCHEMA
REVOKE ALL ON SCHEMA public FROM nasa_write;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM nasa_write;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM nasa_write;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM nasa_write;

-- data SCHEMA
REVOKE ALL ON SCHEMA data FROM nasa_write;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA data FROM nasa_write;
REVOKE ALL ON ALL TABLES IN SCHEMA data FROM nasa_write;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA data FROM nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA data REVOKE ALL ON TABLES FROM nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA data REVOKE ALL ON SEQUENCES FROM nasa_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA data REVOKE ALL ON FUNCTIONS FROM nasa_write;

DROP ROLE nasa_write;
